In [62]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
df = pd.read_csv('/Users/himangini/Desktop/CMPE-257/Assignment1/movie_metadata.csv')
df

color       director_name  num_critic_for_reviews  duration  \
0                Color       James Cameron                   723.0     178.0   
1                Color      Gore Verbinski                   302.0     169.0   
2                Color          Sam Mendes                   602.0     148.0   
3                Color   Christopher Nolan                   813.0     164.0   
4                  NaN         Doug Walker                     NaN       NaN   
5                Color      Andrew Stanton                   462.0     132.0   
6                Color           Sam Raimi                   392.0     156.0   
7                Color        Nathan Greno                   324.0     100.0   
8                Color         Joss Whedon                   635.0     141.0   
9                Color         David Yates                   375.0     153.0   
10               Color         Zack Snyder                   673.0     183.0   
11               Color        Bryan Singer                   434.0     169.0   
12               Color        Marc Forster                   403.0     106.0   
13               Color      Gore Verbinski                   313.0     151.0   
14               Color      Gore Verbinski                   450.0     150.0   
15               Color         Zack Snyder                   733.0     143.0   
16               Color      Andrew Adamson                   258.0     150.0   
17               Color         Joss Whedon                   703.0     173.0   
18               Color        Rob Marshall                   448.0     136.0   
19               Color    Barry Sonnenfeld                   451.0     106.0   
20               Color       Peter Jackson                   422.0     164.0   
21               Color           Marc Webb                   599.0     153.0   
22               Color        Ridley Scott                   343.0     156.0   
23               Color       Peter Jackson                   509.0     186.0   
24               Color         Chris Weitz                   251.0     113.0   
25               Color       Peter Jackson                   446.0     201.0   
26               Color       James Cameron                   315.0     194.0   
27               Color       Anthony Russo                   516.0     147.0   
28               Color          Peter Berg                   377.0     131.0   
29               Color     Colin Trevorrow                   644.0     124.0   
...                ...                 ...                     ...       ...   
5013             Color          Eric Eason                    28.0      79.0   
5014             Color            Uwe Boll                    58.0      80.0   
5015   Black and White   Richard Linklater                    61.0     100.0   
5016             Color     Joseph Mazzella                     NaN      90.0   
5017             Color        Travis Legge                     1.0      90.0   
5018             Color       Alex Kendrick                     5.0     120.0   
5019             Color       Marcus Nispel                    43.0      91.0   
5020               NaN     Brandon Landers                     NaN     143.0   
5021             Color         Jay Duplass                    51.0      85.0   
5022   Black and White          Jim Chuchu                     6.0      60.0   
5023             Color          Daryl Wein                    22.0      88.0   
5024             Color         Jason Trost                    42.0      78.0   
5025             Color         John Waters                    73.0     108.0   
5026             Color     Olivier Assayas                    81.0     110.0   
5027             Color        Jafar Panahi                    64.0      90.0   
5028   Black and White       Ivan Kavanagh                    12.0      83.0   
5029             Color    Kiyoshi Kurosawa                    78.0     111.0   
5030             Color        Tadeo Garcia                     NaN      84.0   
5031             

In [64]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [65]:
df = df.drop(columns=['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'actor_1_name', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes', 'aspect_ratio', 'movie_facebook_likes' ])

In [66]:
df.head()

genres  \
0  Action|Adventure|Fantasy|Sci-Fi   
1         Action|Adventure|Fantasy   
2        Action|Adventure|Thriller   
3                  Action|Thriller   
4                      Documentary   

                                         movie_title  imdb_score  
0                                            Avatar          7.9  
1          Pirates of the Caribbean: At World's End          7.1  
2                                           Spectre          6.8  
3                             The Dark Knight Rises          8.5  
4  Star Wars: Episode VII - The Force Awakens    ...         7.1

In [67]:
def good_movies(imdb_score):
    if imdb_score>5:
        good_movies=1
    else:
        good_movies=0
    return good_movies

In [68]:
print(good_movies(2.3))

0


In [69]:
df['genres'].unique()

array(['Action|Adventure|Fantasy|Sci-Fi', 'Action|Adventure|Fantasy',
       'Action|Adventure|Thriller', 'Action|Thriller', 'Documentary',
       'Action|Adventure|Sci-Fi', 'Action|Adventure|Romance',
       'Adventure|Animation|Comedy|Family|Fantasy|Musical|Romance',
       'Adventure|Family|Fantasy|Mystery', 'Action|Adventure',
       'Action|Adventure|Western', 'Action|Adventure|Family|Fantasy',
       'Action|Adventure|Comedy|Family|Fantasy|Sci-Fi',
       'Adventure|Fantasy', 'Action|Adventure|Drama|History',
       'Adventure|Family|Fantasy', 'Action|Adventure|Drama|Romance',
       'Drama|Romance', 'Action|Adventure|Sci-Fi|Thriller',
       'Action|Adventure|Fantasy|Romance',
       'Action|Adventure|Fantasy|Sci-Fi|Thriller',
       'Adventure|Animation|Comedy|Family|Fantasy',
       'Adventure|Animation|Comedy|Family|Sport', 'Action|Crime|Thriller',
       'Action|Adventure|Horror|Sci-Fi|Thriller',
       'Adventure|Animation|Family|Sci-Fi',
       'Action|Comedy|Crime|Thrille

In [10]:
df['genres'].replace({'Sci-fi': 'Science'}, regex=True, inplace=True)

In [70]:
df

genres  \
0                       Action|Adventure|Fantasy|Sci-Fi   
1                              Action|Adventure|Fantasy   
2                             Action|Adventure|Thriller   
3                                       Action|Thriller   
4                                           Documentary   
5                               Action|Adventure|Sci-Fi   
6                              Action|Adventure|Romance   
7     Adventure|Animation|Comedy|Family|Fantasy|Musi...   
8                               Action|Adventure|Sci-Fi   
9                      Adventure|Family|Fantasy|Mystery   
10                              Action|Adventure|Sci-Fi   
11                              Action|Adventure|Sci-Fi   
12                                     Action|Adventure   
13                             Action|Adventure|Fantasy   
14                             Action|Adventure|Western   
15                      Action|Adventure|Fantasy|Sci-Fi   
16                      Action|Adventure|Family|Fantasy   
17                              Action|Adventure|Sci-Fi   
18                             Action|Adventure|Fantasy   
19        Action|Adventure|Comedy|Family|Fantasy|Sci-Fi   
20                                    Adventure|Fantasy   
21                             Action|Adventure|Fantasy   
22                       Action|Adventure|Drama|History   
23                                    Adventure|Fantasy   
24                             Adventure|Family|Fantasy   
25                       Action|Adventure|Drama|Romance   
26                                        Drama|Romance   
27                              Action|Adventure|Sci-Fi   
28                     Action|Adventure|Sci-Fi|Thriller   
29                     Action|Adventure|Sci-Fi|Thriller   
...                                                 ...   
5013                                       Drama|Family   
5014                              Action|Crime|Thriller   
5015                                       Comedy|Drama   
5016                               Crime|Drama|Thriller   
5017                                     Comedy|Romance   
5018                                              Drama   
5019                            Horror|Mystery|Thriller   
5020                              Drama|Horror|Thriller   
5021                               Comedy|Drama|Romance   
5022                                              Drama   
5023                                            Romance   
5024                                    Sci-Fi|Thriller   
5025                                Comedy|Crime|Horror   
5026                                Drama|Music|Romance   
5027                                              Drama   
5028                                             Horror   
5029                      Crime|Horror|Mystery|Thriller   
5030                                              Drama   
5031                             Comedy|Horror|Thriller   
5032                                        Crime|Drama   
5033                              Drama|Sci-Fi|Thriller   
5034                                           Thriller   
5035                Action|Crime|Drama|Romance|Thriller   
5036                                        Crime|Drama   
5037                                       Comedy|Drama   
5038                                       Comedy|Drama   
5039                       Crime|Drama|Mystery|Thriller   
5040                              Drama|Horror|Thriller   
5041                               Comedy|Drama|Romance   
5042                                        Documentary   

                                            movie_title  imdb_score  
0                                               Avatar          7.9  
1             Pirates of the Caribbean: At World's End          7.1  
2                                              Spectre          6.8  
3                                The Dark Knight Rises          8.5  
4     Star Wars: Episode VII - The Force

In [71]:
df['genres']

0                         Action|Adventure|Fantasy|Sci-Fi
1                                Action|Adventure|Fantasy
2                               Action|Adventure|Thriller
3                                         Action|Thriller
4                                             Documentary
5                                 Action|Adventure|Sci-Fi
6                                Action|Adventure|Romance
7       Adventure|Animation|Comedy|Family|Fantasy|Musi...
8                                 Action|Adventure|Sci-Fi
9                        Adventure|Family|Fantasy|Mystery
10                                Action|Adventure|Sci-Fi
11                                Action|Adventure|Sci-Fi
12                                       Action|Adventure
13                               Action|Adventure|Fantasy
14                               Action|Adventure|Western
15                        Action|Adventure|Fantasy|Sci-Fi
16                        Action|Adventure|Family|Fantasy
17            

In [72]:
test_text_data = df['genres']

In [73]:
vectorizer = CountVectorizer()
vectorizer.fit(test_text_data)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [74]:
print(vectorizer.vocabulary_)

{'action': 0, 'adventure': 1, 'fantasy': 9, 'sci': 22, 'fi': 10, 'thriller': 26, 'documentary': 6, 'romance': 21, 'animation': 2, 'comedy': 4, 'family': 8, 'musical': 16, 'mystery': 17, 'western': 29, 'drama': 7, 'history': 13, 'sport': 25, 'crime': 5, 'horror': 14, 'war': 28, 'biography': 3, 'music': 15, 'game': 12, 'show': 24, 'reality': 20, 'tv': 27, 'news': 18, 'short': 23, 'film': 11, 'noir': 19}


In [75]:
vectorizer.get_feature_names()

['action',
 'adventure',
 'animation',
 'biography',
 'comedy',
 'crime',
 'documentary',
 'drama',
 'family',
 'fantasy',
 'fi',
 'film',
 'game',
 'history',
 'horror',
 'music',
 'musical',
 'mystery',
 'news',
 'noir',
 'reality',
 'romance',
 'sci',
 'short',
 'show',
 'sport',
 'thriller',
 'tv',
 'war',
 'western']

In [76]:
bag_of_words=vectorizer.transform(test_text_data)

In [77]:
print(bag_of_words)

  (0, 0)	1
  (0, 1)	1
  (0, 9)	1
  (0, 10)	1
  (0, 22)	1
  (1, 0)	1
  (1, 1)	1
  (1, 9)	1
  (2, 0)	1
  (2, 1)	1
  (2, 26)	1
  (3, 0)	1
  (3, 26)	1
  (4, 6)	1
  (5, 0)	1
  (5, 1)	1
  (5, 10)	1
  (5, 22)	1
  (6, 0)	1
  (6, 1)	1
  (6, 21)	1
  (7, 1)	1
  (7, 2)	1
  (7, 4)	1
  (7, 8)	1
  :	:
  (5033, 22)	1
  (5033, 26)	1
  (5034, 26)	1
  (5035, 0)	1
  (5035, 5)	1
  (5035, 7)	1
  (5035, 21)	1
  (5035, 26)	1
  (5036, 5)	1
  (5036, 7)	1
  (5037, 4)	1
  (5037, 7)	1
  (5038, 4)	1
  (5038, 7)	1
  (5039, 5)	1
  (5039, 7)	1
  (5039, 17)	1
  (5039, 26)	1
  (5040, 7)	1
  (5040, 14)	1
  (5040, 26)	1
  (5041, 4)	1
  (5041, 7)	1
  (5041, 21)	1
  (5042, 6)	1


In [78]:
print(bag_of_words.toarray())

[[1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
df['imdb_score']

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
5       6.6
6       6.2
7       7.8
8       7.5
9       7.5
10      6.9
11      6.1
12      6.7
13      7.3
14      6.5
15      7.2
16      6.6
17      8.1
18      6.7
19      6.8
20      7.5
21      7.0
22      6.7
23      7.9
24      6.1
25      7.2
26      7.7
27      8.2
28      5.9
29      7.0
       ... 
5013    7.0
5014    6.3
5015    7.1
5016    4.8
5017    3.3
5018    6.9
5019    4.6
5020    3.0
5021    6.6
5022    7.4
5023    6.2
5024    4.0
5025    6.1
5026    6.9
5027    7.5
5028    6.7
5029    7.4
5030    6.1
5031    5.4
5032    6.4
5033    7.0
5034    6.3
5035    6.9
5036    7.8
5037    6.4
5038    7.7
5039    7.5
5040    6.3
5041    6.3
5042    6.6
Name: imdb_score, Length: 5043, dtype: float64

In [79]:
df['imdb_score'] = df['imdb_score']#.apply(good_movies)

In [80]:
df['imdb_score']

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
5       6.6
6       6.2
7       7.8
8       7.5
9       7.5
10      6.9
11      6.1
12      6.7
13      7.3
14      6.5
15      7.2
16      6.6
17      8.1
18      6.7
19      6.8
20      7.5
21      7.0
22      6.7
23      7.9
24      6.1
25      7.2
26      7.7
27      8.2
28      5.9
29      7.0
       ... 
5013    7.0
5014    6.3
5015    7.1
5016    4.8
5017    3.3
5018    6.9
5019    4.6
5020    3.0
5021    6.6
5022    7.4
5023    6.2
5024    4.0
5025    6.1
5026    6.9
5027    7.5
5028    6.7
5029    7.4
5030    6.1
5031    5.4
5032    6.4
5033    7.0
5034    6.3
5035    6.9
5036    7.8
5037    6.4
5038    7.7
5039    7.5
5040    6.3
5041    6.3
5042    6.6
Name: imdb_score, Length: 5043, dtype: float64

In [81]:
df

genres  \
0                       Action|Adventure|Fantasy|Sci-Fi   
1                              Action|Adventure|Fantasy   
2                             Action|Adventure|Thriller   
3                                       Action|Thriller   
4                                           Documentary   
5                               Action|Adventure|Sci-Fi   
6                              Action|Adventure|Romance   
7     Adventure|Animation|Comedy|Family|Fantasy|Musi...   
8                               Action|Adventure|Sci-Fi   
9                      Adventure|Family|Fantasy|Mystery   
10                              Action|Adventure|Sci-Fi   
11                              Action|Adventure|Sci-Fi   
12                                     Action|Adventure   
13                             Action|Adventure|Fantasy   
14                             Action|Adventure|Western   
15                      Action|Adventure|Fantasy|Sci-Fi   
16                      Action|Adventure|Family|Fantasy   
17                              Action|Adventure|Sci-Fi   
18                             Action|Adventure|Fantasy   
19        Action|Adventure|Comedy|Family|Fantasy|Sci-Fi   
20                                    Adventure|Fantasy   
21                             Action|Adventure|Fantasy   
22                       Action|Adventure|Drama|History   
23                                    Adventure|Fantasy   
24                             Adventure|Family|Fantasy   
25                       Action|Adventure|Drama|Romance   
26                                        Drama|Romance   
27                              Action|Adventure|Sci-Fi   
28                     Action|Adventure|Sci-Fi|Thriller   
29                     Action|Adventure|Sci-Fi|Thriller   
...                                                 ...   
5013                                       Drama|Family   
5014                              Action|Crime|Thriller   
5015                                       Comedy|Drama   
5016                               Crime|Drama|Thriller   
5017                                     Comedy|Romance   
5018                                              Drama   
5019                            Horror|Mystery|Thriller   
5020                              Drama|Horror|Thriller   
5021                               Comedy|Drama|Romance   
5022                                              Drama   
5023                                            Romance   
5024                                    Sci-Fi|Thriller   
5025                                Comedy|Crime|Horror   
5026                                Drama|Music|Romance   
5027                                              Drama   
5028                                             Horror   
5029                      Crime|Horror|Mystery|Thriller   
5030                                              Drama   
5031                             Comedy|Horror|Thriller   
5032                                        Crime|Drama   
5033                              Drama|Sci-Fi|Thriller   
5034                                           Thriller   
5035                Action|Crime|Drama|Romance|Thriller   
5036                                        Crime|Drama   
5037                                       Comedy|Drama   
5038                                       Comedy|Drama   
5039                       Crime|Drama|Mystery|Thriller   
5040                              Drama|Horror|Thriller   
5041                               Comedy|Drama|Romance   
5042                                        Documentary   

                                            movie_title  imdb_score  
0                                               Avatar          7.9  
1             Pirates of the Caribbean: At World's End          7.1  
2                                              Spectre          6.8  
3                                The Dark Knight Rises          8.5  
4     Star Wars: Episode VII - The Force

In [82]:
X = bag_of_words
Y = df.imdb_score
print(X.shape)
print(Y.shape)

(5043, 30)
(5043,)


In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 0)

In [84]:
print(vectorizer.vocabulary_)

{'action': 0, 'adventure': 1, 'fantasy': 9, 'sci': 22, 'fi': 10, 'thriller': 26, 'documentary': 6, 'romance': 21, 'animation': 2, 'comedy': 4, 'family': 8, 'musical': 16, 'mystery': 17, 'western': 29, 'drama': 7, 'history': 13, 'sport': 25, 'crime': 5, 'horror': 14, 'war': 28, 'biography': 3, 'music': 15, 'game': 12, 'show': 24, 'reality': 20, 'tv': 27, 'news': 18, 'short': 23, 'film': 11, 'noir': 19}


In [85]:
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [86]:
print (regr.intercept_)

6.432473971244422


In [87]:
print(regr.coef_)

[-0.247373    0.1655529   0.553436    0.27811969 -0.34502852  0.14783837
  0.81267708  0.46498888 -0.36918485  0.06126513  0.0396452   0.49513796
 -1.79001983  0.11485272 -0.51959786 -0.31341054  0.04237184  0.06375157
  0.06492816  0.49513796  0.07716994 -0.10677419  0.0396452  -0.23058163
 -1.79001983 -0.0230162  -0.24170725  0.07716994  0.23046505  0.09773824]


In [88]:
y_pred = regr.predict(X_test)

In [89]:
pred = pd.DataFrame({'Actual':y_pred,'Expected':Y_test})

In [90]:
pred

Actual  Expected
3937  6.958728       7.1
3382  6.655756       7.0
1965  6.235284       5.1
3819  6.676125       7.4
2172  6.412554       7.1
3277  5.992166       8.5
2062  6.552434       6.1
4881  5.671169       4.4
3701  5.912876       5.8
3046  5.992166       5.5
4171  6.790689       7.8
113   7.332306       5.5
381   6.081463       6.2
2689  6.790689       7.0
1986  6.408383       5.8
2971  7.340519       6.0
3388  6.445660       7.1
1196  5.734920       7.8
2816  6.897463       6.5
4300  6.517143       7.4
2940  5.976628       5.4
4626  6.655756       3.9
556   6.614195       6.6
1865  6.612733       7.5
534   6.402357       7.3
2518  6.060759       3.6
2806  7.290435       6.7
4293  6.552434       6.4
2545  6.445660       8.0
265   6.706364       7.1
...        ...       ...
4958  7.045301       4.8
3575  6.264391       8.1
3263  6.452900       6.0
4338  7.245151       5.3
9     6.353859       7.5
4759  6.235284       7.7
4888  7.076048       7.1
1615  6.635511       7.4
3539  6.474423       6.0
3689  6.552434       7.7
3746  6.552434       7.2
3079  6.741069       8.3
1749  6.350654       7.6
4825  6.655756       7.3
4745  6.445660       6.1
3823  5.912876       5.9
253   6.995408       7.1
3787  6.700273       7.1
3780  7.045301       6.8
3124  5.987911       5.8
4395  6.445660       7.3
4431  6.087445       6.1
720   7.629024       7.0
938   5.980671       6.4
122   5.945079       5.9
4908  5.750459       3.9
4876  6.790645       7.0
4121  7.242781       5.9
829   6.411919       6.4
87    6.498515       6.4

[1009 rows x 2 columns]

In [91]:
from sklearn import metrics
print('Mean Absolute:', metrics.mean_absolute_error(Y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test,y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test,y_pred)))

Mean Absolute: 0.7792699066937984
Mean Squared Error: 1.052217519283196
Root Mean Squared Error: 1.025776544517955
